
translation_dict = {
        'मझु': 'mujhe',
        'सिर्फ': 'sirf',
        'minute': 'minute',
        'का': 'ka',
        'डेमो': 'demo',
        'मिला': 'mila',
        'था': 'tha',
        'इस': 'is',
        'नये': 'nye',
        'हेडसेट': 'headset',
        'का': 'ka',
        'इस्तेमाल': 'istemal',
        'करने': 'karne',
        'के': 'ke',
        'लिए': 'liye',
        'में': 'mein',
        'सेकंड': 'second',
        'हुआ': 'hua',
        'जब': 'jab',
        'हम': 'hum',
        'सुना': 'suna',
        'खुशी': 'khushi',
        'बच्चा': 'bachcha',
        'स्कूल': 'school',
        'पढ़ाई': 'padhai',
        'मैं': 'main',
        'सोया': 'soya',
        'रात': 'raat',
        'की': 'ki',
        'खाना': 'khana',
        'बनाया': 'banaya',
        'मां': 'maa',
        'पापा': 'papa',
        'मेरा': 'mera',
        'प्यार': 'pyaar',
        'बहुत': 'bahut',
        'अच्छा': 'achha',
        'दिन': 'din',
        'सब': 'sab',
        'समय': 'samay',
        'समझ': 'samajh',
        'डेटाबेस': 'database',
        'वेबसाइट': 'website',
        'सर्वर': 'server',
        'कंप्यूटर': 'computer',
        'सॉफ़्टवेयर': 'software',
        'हार्डवेयर': 'hardware',
        'इंटरनेट': 'internet',
        'प्रोग्रामिंग': 'programming',
        'मशीन लर्निंग': 'machine learning',
        'कृत्रिम बुद्धि': 'artificial intelligence',
        'न्यूरल नेटवर्क': 'neural network',
        'डीप लर्निंग': 'deep learning',
        'डेटा विज्ञान': 'data science',
        'सुपरवाइज्ड लर्निंग': 'supervised learning',
        'अनुपेक्षित लर्निंग': 'unsupervised learning',
         'मशीन लर्निंग': 'machine learning',
        'कृत्रिम बुद्धि': 'artificial intelligence',
        'न्यूरल नेटवर्क': 'neural network',
        'डीप लर्निंग': 'deep learning',
        'डेटा विज्ञान': 'data science',
        'सुपरवाइज्ड लर्निंग': 'supervised learning',
        'अनुपेक्षित लर्निंग': 'unsupervised learning',
        'रिएक्ट नेटवर्क': 'react network',
        'नेचुरल लैंग्वेज प्रोसेसिंग': 'natural language processing',
        'डेटा माइनिंग': 'data mining',
        'अल्गोरिदम': 'algorithm',
        'फीचर': 'feature',
        'ट्रेनिंग डेटा': 'training data',
        'टेस्ट डेटा': 'test data',
        'हाइपरपैरामीटर': 'hyperparameter',
        'ऑवरफिटिंग': 'overfitting',
        'अंडरफिटिंग': 'underfitting',
        'क्लासिफिकेशन': 'classification',
        'रिग्रेशन': 'regression',
        'क्लस्टरिंग': 'clustering',
        'डिप लर्निंग': 'deep learning',
        'न्यूरल लैंग्वेज प्रोसेसिंग': 'natural language processing',
        'कंप्यूटर विज़न': 'computer vision',
        'रिकर्सिव नेटवर्क': 'recursive network',
        'आर्टिफिशियल न्यूरल नेटवर्क': 'artificial neural network',
        'ग्रेडिएंट डीसेंट': 'gradient descent',
        'रिन्फोर्समेंट लर्निंग': 'reinforcement learning',
        'गैन फ़ंक्शन': 'gain function',
        'एक्सप्लेनेबिलिटी': 'explainability',
        'डीप रीडिंग': 'deep reading',
        'लेयर': 'layer',
        'फीडफ़ॉरवर्ड नेटवर्क': 'feedforward network',
        'लॉस फ़ंक्शन': 'loss function',
        'वादित': 'biased',
        'अवादित': 'unbiased',
        'फ़ीचर इंजीनियरिंग': 'feature engineering',
        'दीप रीडिंग': 'deep reading',
        'कॉनवल्यूशनल नेटवर्क': 'convolutional network',
        'रिग्रेशन ट्री': 'regression tree',
        'बूस्टिंग': 'boosting',
        'बैगिंग': 'bagging',
        'एन्सेंबल': 'ensemble',
        'फीचर स्केलिंग': 'feature scaling',
        'फ़ोटो': 'photo',
        'वीडियो': 'video',
        'फीड': 'feed',
        'पोस्ट': 'post',
        'लाइक': 'like',
        'शेयर': 'share',
        'कमेंट': 'comment',
        'ट्वीट': 'tweet',
        'हैशटैग': 'hashtag',
        'फ़ॉलोवर्स': 'followers',
        'फ़ॉलोइंग': 'following',
        'प्रोफ़ाइल': 'profile',
        'ब्लॉग': 'blog',
        'सोशल मीडिया': 'social media',
        'सोशल नेटवर्क': 'social network',
        'वर्चुअल रियलिटी': 'virtual reality',
        'लाइव स्ट्रीम': 'live stream',
        'मैसेंजर': 'messenger',
        'स्टोरी': 'story',
        'स्क्रीनशॉट': 'screenshot',
        'फॉलोबैक': 'follow back',
     
    }

